# Generated by Django 4.0.6 on 2022-08-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribed_to_newsletter',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
