# Generated by Django 4.0.6 on 2022-08-05 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_subscribed_to_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscribed_to_newsletter',
        ),
    ]
