# Generated by Django 4.0.6 on 2022-08-15 12:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_url', models.URLField(unique=True)),
                ('document_name', models.CharField(max_length=224)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('consent', models.BooleanField(blank=True, null=True)),
                ('info_we_collect', models.BooleanField(blank=True, null=True)),
                ('how_we_use_info', models.BooleanField(blank=True, null=True)),
                ('cookies', models.BooleanField(blank=True, null=True)),
                ('advertising_partners', models.BooleanField(blank=True, null=True)),
                ('third_party', models.BooleanField(blank=True, null=True)),
                ('children_information', models.BooleanField(blank=True, null=True)),
                ('permanent', models.BooleanField(blank=True, null=True)),
                ('create_date', models.DateTimeField(null=True)),
                ('last_edit', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['last_edit'],
            },
        ),
    ]
