# Generated by Django 4.0.6 on 2022-08-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_p', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='adapt_to_calopa',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='adapt_to_ccpa',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='adapt_to_gdpr',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='business_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='last_edit',
            field=models.DateTimeField(null=True),
        ),
    ]
