# Generated by Django 4.0.6 on 2022-08-05 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_p', '0003_alter_privacypolicy_adapt_to_calopa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypolicy',
            name='adapt_to_calopa',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='adapt_to_ccpa',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='adapt_to_gdpr',
        ),
    ]
