# Generated by Django 4.0.6 on 2022-08-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_p', '0003_alter_privacypolicy_business_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='business_url',
            field=models.URLField(unique=True),
        ),
    ]
