# Generated by Django 4.0.6 on 2022-08-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_p', '0004_remove_privacypolicy_adapt_to_calopa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypolicy',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='captcha_service',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='country',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='marketing_services',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='state',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='tracking_services',
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='advertising_partners',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='children_information',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='consent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='cookies',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='how_we_use_info',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='info_we_collect',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='third_party',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
