# Generated by Django 4.0.6 on 2022-08-08 13:04

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('business_url', models.URLField(unique=True)),
                ('document_name', models.CharField(blank=True, max_length=224, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('cookies', models.BooleanField(blank=True, null=True)),
                ('licenses', models.BooleanField(blank=True, null=True)),
                ('content_liability', models.BooleanField(blank=True, null=True)),
                ('iframes', models.BooleanField(blank=True, null=True)),
                ('disclaimer', models.BooleanField(blank=True, null=True)),
                ('additional_text', models.TextField(blank=True, null=True)),
                ('permanent', models.BooleanField()),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('last_edit', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['last_edit'],
            },
        ),
    ]
