# Generated by Django 4.0.6 on 2022-08-04 23:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('t_c', '0003_alter_terms_business_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='age_limit',
            field=models.IntegerField(blank=True, default=13, null=True),
        ),
        migrations.AlterField(
            model_name='terms',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terms',
            name='last_edit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terms',
            name='permanent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
